"""Markdown report generator."""

from __future__ import annotations

from medusa.core.models import ScanResult, Severity, Status
from medusa.reporters.base import BaseReporter


class MarkdownReporter(BaseReporter):
    """Generate Markdown report output."""

    def generate(self, result: ScanResult) -> str:
        lines: list[str] = []

        # Header
        lines.append("# Medusa MCP Security Scan Report")
        lines.append("")
        lines.append(
            f"**Date:** {result.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')} | "
            f"**Grade:** {result.aggregate_grade} ({result.aggregate_score}/10) | "
            f"**Servers:** {result.servers_scanned}"
        )
        lines.append("")

        # Summary table
        severity_counts = self._count_by_severity(result)
        lines.append("## Summary")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in ["critical", "high", "medium", "low"]:
            count = severity_counts.get(sev, 0)
            lines.append(f"| {sev.capitalize()} | {count} |")
        lines.append("")

        # Server scores
        if result.server_scores:
            lines.append("## Server Scores")
            lines.append("")
            lines.append("| Server | Score | Grade | Failed |")
            lines.append("|--------|-------|-------|--------|")
            for ss in result.server_scores:
                lines.append(f"| {ss.server_name} | {ss.score}/10 | {ss.grade} | {ss.failed} |")
            lines.append("")

        # Findings
        failed_findings = [f for f in result.findings if f.status == Status.FAIL]
        if failed_findings:
            lines.append("## Findings")
            lines.append("")

            # Group by severity
            for severity in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
                sev_findings = [f for f in failed_findings if f.severity == severity]
                if not sev_findings:
                    continue

                for finding in sev_findings:
                    lines.append(
                        f"### [{severity.value.upper()}] {finding.check_id}: {finding.check_title}"
                    )
                    lines.append("")
                    lines.append(
                        f"- **Server:** {finding.server_name} ({finding.server_transport})"
                    )
                    lines.append(f"- **Resource:** {finding.resource_type}/{finding.resource_name}")
                    lines.append(f"- **Details:** {finding.status_extended}")
                    if finding.evidence:
                        evidence_preview = finding.evidence[:500]
                        if len(finding.evidence) > 500:
                            evidence_preview += "..."
                        lines.append(f"- **Evidence:** `{evidence_preview}`")
                    lines.append(f"- **Remediation:** {finding.remediation}")
                    if finding.owasp_mcp:
                        lines.append(f"- **OWASP MCP:** {', '.join(finding.owasp_mcp)}")
                    lines.append("")
        else:
            lines.append("## Findings")
            lines.append("")
            lines.append("No security findings detected. All checks passed.")
            lines.append("")

        # Compliance
        if result.compliance_results:
            lines.append("## Compliance")
            lines.append("")
            for framework_name, requirements in result.compliance_results.items():
                lines.append(f"### {framework_name}")
                lines.append("")
                lines.append("| Requirement | Status | Passed | Failed |")
                lines.append("|-------------|--------|--------|--------|")
                for req_id, req_data in requirements.items():
                    status_icon = {
                        "compliant": "PASS",
                        "non_compliant": "FAIL",
                        "not_assessed": "N/A",
                    }.get(req_data["status"], "?")
                    lines.append(
                        f"| {req_id}: {req_data['title']} | {status_icon} | "
                        f"{req_data['checks_passed']} | {req_data['checks_failed']} |"
                    )
                lines.append("")

        # Footer
        lines.append("---")
        lines.append(
            f"*Generated by Medusa v{result.medusa_version} in {result.scan_duration_seconds}s*"
        )
        lines.append("")

        return "\n".join(lines)

    def _count_by_severity(self, result: ScanResult) -> dict[str, int]:
        counts: dict[str, int] = {}
        for f in result.findings:
            if f.status == Status.FAIL:
                sev = f.severity.value
                counts[sev] = counts.get(sev, 0) + 1
        return counts
